language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt

script:
  - pytest
  - echo "$ip ecdsa-sha2-nistp256 $pub_key" >> $HOME/.ssh/known_hosts

before_deploy:
  - openssl aes-256-cbc -K $encrypted_775290d4779d_key -iv $encrypted_775290d4779d_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh $user@$ip && cd /root/code
  on:
    branch: master
